# -*- coding: utf-8 -*-
"""477 Project Work Pre Pivot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKQvwZ4U_I38uPkHdEbd2_pgIfx8HeQC
"""

import pandas as pd

df1 = pd.read_csv('breast-cancer-wisconsin.data', header=None)  # or add names=[...] if you know them
df1.to_csv('breast-cancer.csv', index=False)

df1[0].head()

df = pd.read_csv('wdbc.data', header=None)  # or add names=[...] if you know them
df.to_csv('wdbc.csv', index=False)

df[0].head()

import pandas as pd

df1 = pd.read_csv('breast-cancer-wisconsin.data', header=None)
df2 = pd.read_csv('wdbc.data', header=None)

ids1 = set(df1[0].dropna().astype(str))
ids2 = set(df2[0].dropna().astype(str))

common_ids = ids1.intersection(ids2)
unique1 = ids1 - ids2
unique2 = ids2 - ids1

print(f"Number of IDs in dataset 1: {len(ids1)}")
print(f"Number of IDs in dataset 2: {len(ids2)}")
print(f"Number of overlapping IDs: {len(common_ids)}")

