# -*- coding: utf-8 -*-
"""477 Project Work New Dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHaJlQkKsUWZo4NtQgNq8kSHhoLG83dJ
"""

import pandas as pd

df1 = pd.read_csv("hf://datasets/maharshipandya/spotify-tracks-dataset/dataset.csv")
len(df1)

df2 = pd.read_csv('songs_normalize.csv')
len(df2)

# Standardize name columns
df1['track_name_clean'] = df1['track_name'].str.lower().str.strip()
df1['artist_clean'] = df1['artists'].str.lower().str.strip()

df2['song_clean'] = df2['song'].str.lower().str.strip()
df2['artist_clean'] = df2['artist'].str.lower().str.strip()

merged_exact = df1.merge(
    df2,
    left_on=['artist_clean', 'track_name_clean'],
    right_on=['artist_clean', 'song_clean'],
    how='inner'
)

len(merged_exact)

merged_exact.columns

merged_exact['popularity_x']

merged_exact['popularity_y']

