# -*- coding: utf-8 -*-
"""477 Project Work New Dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHaJlQkKsUWZo4NtQgNq8kSHhoLG83dJ
"""

import pandas as pd
import kaggle
import os 

df1 = pd.read_csv("hf://datasets/maharshipandya/spotify-tracks-dataset/dataset.csv")
len(df1)

kaggle.api.authenticate()
kaggle.api.dataset_download_files("sansastark/subset-of-the-million-song-dataset", path='.', unzip=True)
os.remove("billboard_rank.csv")
df2 = pd.read_csv("MillionSongSubset.csv")

# Standardize name columns
df1['track_name_clean'] = df1['track_name'].str.lower().str.strip()
df1['artist_clean'] = df1['artists'].str.lower().str.strip()

df2['song_clean'] = df2['Title'].str.lower().str.strip()
df2['artist_clean'] = df2['ArtistName'].str.lower().str.strip()

merged_exact = df1.merge(
    df2,
    left_on=['artist_clean', 'track_name_clean'],
    right_on=['artist_clean', 'song_clean'],
    how='inner'
)

print(len(merged_exact))

print(merged_exact.columns)

